### ISSUE TITLE
Could not resolve composable

### ISSUE THREAD

**Issue by hamzstramgram** [mathieustan/vue-intercom#5]
Hello,

Trying to use the plugin with Vue 3 Typescript. So currently the `"@mathieustan/vue-intercom": "^1.0.0-alpha.0"`

For some reason after I `npm i` the alpha package does not contain the "composable" folder and it results in this error:

```
✘ [ERROR] Could not resolve "./composables"

    node_modules/@mathieustan/vue-intercom/lib/index.mjs:2:45:
      2 │ import { initIntercom, IntercomSymbol } from "./composables";
        ╵                                              ~~~~~~~~~~~~~~~

/app/node_modules/esbuild/lib/main.js:1591
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
node_modules/@mathieustan/vue-intercom/lib/index.mjs:2:45: ERROR: Could not resolve "./composables"
    at failureErrorWithLog (/app/node_modules/esbuild/lib/main.js:1591:15)
    at /app/node_modules/esbuild/lib/main.js:1047:28
    at runOnEndCallbacks (/app/node_modules/esbuild/lib/main.js:1463:61)
    at buildResponseToResult (/app/node_modules/esbuild/lib/main.js:1045:7)
    at /app/node_modules/esbuild/lib/main.js:1157:14
    at responseCallbacks.<computed> (/app/node_modules/esbuild/lib/main.js:694:9)
    at handleIncomingPacket (/app/node_modules/esbuild/lib/main.js:749:9)
    at Socket.readFromStdout (/app/node_modules/esbuild/lib/main.js:670:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 45,
        file: 'node_modules/@mathieustan/vue-intercom/lib/index.mjs',
        length: 15,
        line: 2,
        lineText: 'import { initIntercom, IntercomSymbol } from "./composables";',
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'Could not resolve "./composables"'
    }
  ],
  warnings: []
}

```

Thank for the help !

**Comment by NicolasRotier** [comment]
I have the same problem

**Comment by josechiesa** [comment]
got the exact same error, please fix this asap 😢

**Comment by cydd007** [comment]
I have the same problem

**Comment by mathieustan** [comment]
It should be fixed:  https://github.com/mathieustan/vue-intercom/releases/tag/%40mathieustan%2Fvue-intercom%401.0.0-alpha.2

Sorry for this very long delay. I don't have much time for this.
